server:
  port: 5001

spring:
  application:
    name: USER-SERVICE


  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: Akhil@123
    driver-class-name: com.mysql.cj.jdbc.Driver
